### ISSUE TITLE
ActionSheetStringPicker.h not found

### ISSUE THREAD

**Issue by homanp** [4Catalyzer/react-native-actionsheet-picker#2]
Following the install guide and getting `ActionSheetStringPicker.h not found` error.

Any suggestions?

**Comment by chirag04** [comment]
did you do pod install? can you also make sure `libraries -> actionsheetpicker -> build settings -> header search path` for pods is correct.

**Comment by homanp** [comment]
Yes did the pod install. 
Will check the build settings.

**Comment by homanp** [comment]
<img width="833" alt="screen shot 2016-05-25 at 22 55 27" src="https://cloud.githubusercontent.com/assets/2464556/15556015/d7ced4ae-22cb-11e6-8801-c870e11e6572.png">

These are the search paths. They seem correct.

**Comment by chirag04** [comment]
that doesn't look completely correct. y do you have ios/Pods in your search paths? You need to open `xcworkspace` instead of xcode project file
